import 'user_profile.dart';

class MockProfiles {
  static List<UserProfile> getProfiles() {
    return [
      UserProfile(
        id: '1',
        displayName: 'Priya',
        fullName: 'Priya Sharma',
        avatarUrl: null,
        gender: 'Female',
        dateOfBirth: DateTime(1995, 5, 15),
        bio: 'I am a software engineer who loves traveling and exploring new cultures. I enjoy reading books, cooking, and spending time with family.',
        residenceCity: 'Colombo',
        residenceCountry: 'Sri Lanka',
        profession: 'Software Engineer',
        highestEducation: 'Bachelor\'s Degree',
        careerLevel: 'Mid-level',
        maritalStatus: 'Never Married',
        ethnicity: 'Sinhalese',
        religion: 'Buddhist',
        caste: 'Govigama',
        spokenLanguages: ['Sinhala', 'English', 'Tamil'],
        personalityType: 'Introvert',
        heightCm: 165,
        weightKg: 58,
        bodyType: 'Slim',
        complexion: 'Fair',
        dietaryPreference: 'Vegetarian',
        drinking: 'Socially',
        smoking: 'Never',
        hobbies: ['Reading', 'Traveling', 'Cooking', 'Yoga'],
        idealPartnerDescription: 'Looking for someone who is kind, understanding, and family-oriented. Should share similar values and interests in travel and culture.',
      ),
      UserProfile(
        id: '2',
        displayName: 'Ravi',
        fullName: 'Ravi Perera',
        avatarUrl: null,
        gender: 'Male',
        dateOfBirth: DateTime(1992, 8, 22),
        bio: 'Business professional with a passion for entrepreneurship. I enjoy playing cricket, reading business books, and networking.',
        residenceCity: 'Kandy',
        residenceCountry: 'Sri Lanka',
        profession: 'Business Manager',
        highestEducation: 'Master\'s Degree',
        careerLevel: 'Senior',
        maritalStatus: 'Never Married',
        ethnicity: 'Sinhalese',
        religion: 'Buddhist',
        caste: 'Karava',
        spokenLanguages: ['Sinhala', 'English'],
        personalityType: 'Extrovert',
        heightCm: 178,
        weightKg: 75,
        bodyType: 'Athletic',
        complexion: 'Wheatish',
        dietaryPreference: 'Non-Vegetarian',
        drinking: 'Occasionally',
        smoking: 'Never',
        hobbies: ['Cricket', 'Reading', 'Networking', 'Traveling'],
        idealPartnerDescription: 'Seeking a life partner who is educated, independent, and shares similar family values. Someone who appreciates both traditional and modern lifestyle.',
      ),
      UserProfile(
        id: '3',
        displayName: 'Anjali',
        fullName: 'Anjali Fernando',
        avatarUrl: null,
        gender: 'Female',
        dateOfBirth: DateTime(1994, 3, 10),
        bio: 'Doctor by profession, love helping others. Enjoy classical music, dancing, and spending quality time with loved ones.',
        residenceCity: 'Galle',
        residenceCountry: 'Sri Lanka',
        profession: 'Doctor',
        highestEducation: 'Doctorate',
        careerLevel: 'Senior',
        maritalStatus: 'Never Married',
        ethnicity: 'Sinhalese',
        religion: 'Catholic',
        caste: 'Salagama',
        spokenLanguages: ['Sinhala', 'English'],
        personalityType: 'Ambivert',
        heightCm: 162,
        weightKg: 55,
        bodyType: 'Slim',
        complexion: 'Fair',
        dietaryPreference: 'Non-Vegetarian',
        drinking: 'Never',
        smoking: 'Never',
        hobbies: ['Classical Music', 'Dancing', 'Reading', 'Traveling'],
        idealPartnerDescription: 'Looking for a caring, respectful partner who values family and understands the demands of a medical profession. Should be supportive and understanding.',
      ),
      UserProfile(
        id: '4',
        displayName: 'Dilshan',
        fullName: 'Dilshan Silva',
        avatarUrl: null,
        gender: 'Male',
        dateOfBirth: DateTime(1990, 11, 5),
        bio: 'Engineer and tech enthusiast. Love coding, playing guitar, and exploring new technologies. Family-oriented person.',
        residenceCity: 'Negombo',
        residenceCountry: 'Sri Lanka',
        profession: 'Senior Engineer',
        highestEducation: 'Master\'s Degree',
        careerLevel: 'Senior',
        maritalStatus: 'Never Married',
        ethnicity: 'Sinhalese',
        religion: 'Buddhist',
        caste: 'Durava',
        spokenLanguages: ['Sinhala', 'English'],
        personalityType: 'Introvert',
        heightCm: 175,
        weightKg: 72,
        bodyType: 'Average',
        complexion: 'Wheatish',
        dietaryPreference: 'Non-Vegetarian',
        drinking: 'Socially',
        smoking: 'Never',
        hobbies: ['Coding', 'Guitar', 'Technology', 'Gaming'],
        idealPartnerDescription: 'Seeking someone who is intelligent, kind-hearted, and shares similar interests. Should appreciate both tech and traditional values.',
      ),
      UserProfile(
        id: '5',
        displayName: 'Nisha',
        fullName: 'Nisha Jayasuriya',
        avatarUrl: null,
        gender: 'Female',
        dateOfBirth: DateTime(1996, 7, 18),
        bio: 'Marketing professional who loves creativity and innovation. Enjoy painting, photography, and exploring art galleries.',
        residenceCity: 'Jaffna',
        residenceCountry: 'Sri Lanka',
        profession: 'Marketing Manager',
        highestEducation: 'Bachelor\'s Degree',
        careerLevel: 'Mid-level',
        maritalStatus: 'Never Married',
        ethnicity: 'Tamil',
        religion: 'Hindu',
        caste: 'Vellalar',
        spokenLanguages: ['Tamil', 'English', 'Sinhala'],
        personalityType: 'Extrovert',
        heightCm: 160,
        weightKg: 56,
        bodyType: 'Slim',
        complexion: 'Fair',
        dietaryPreference: 'Vegetarian',
        drinking: 'Never',
        smoking: 'Never',
        hobbies: ['Painting', 'Photography', 'Art', 'Traveling'],
        idealPartnerDescription: 'Looking for a creative, understanding partner who appreciates art and culture. Should be supportive of my career and interests.',
      ),
    ];
  }
}

